"""add tradelint

Revision ID: 59d78d2c5404
Revises: ed5675d24f1b
Create Date: 2026-07-05 03:37:26.947630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59d78d2c5404'
down_revision: Union[str, Sequence[str], None] = 'ed5675d24f1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('steam_id', sa.String(), nullable=True))
    op.add_column('user', sa.Column('trade_ling', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'user', ['trade_ling'])
    op.create_unique_constraint(None, 'user', ['steam_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'trade_ling')
    op.drop_column('user', 'steam_id')
    # ### end Alembic commands ###
